name: Go

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: "go.mod"

    - name: Build
      run: GOOS=${{ matrix.os }};GOARCH=${{ matrix.arch }}; go build -o ./output/sshconfig-1password-${{ matrix.os }}-${{ matrix.arch }} -v .
       
    - name: Archive build articfacts
      uses: actions/upload-artifact@v3
      with:
        path: output
