name: Go

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: "go.mod"

    - name: Install dependencies
      run: go get .

    - name: Run tests
      run: GOOS=${{ matrix.os }};GOARCH=${{ matrix.arch }}; go test -json > TestResults-${{ matrix.os }}-${{ matrix.arch }}.json

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: Go-Results-${{ matrix.os }}-${{ matrix.arch }}
        path: TestResults-${{ matrix.os }}-${{ matrix.arch }}.json

    - name: Build
      run: GOOS=${{ matrix.os }};GOARCH=${{ matrix.arch }}; go build -ldflags "-X main.gitHash=$GIT_COMMIT" -o sshconfig-1password-${{ matrix.os }}-${{ matrix.arch }} -v .
       
    - name: Archive build articfacts
      uses: actions/upload-artifact@v3
      with:
        name: sshconfig-1password-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          sshconfig-1password-${{ matrix.os }}-${{ matrix.arch }}
          LICENSE
          README.md
